-- MySQL Script generated by MySQL Workbench
-- mar 18 abr 2023 17:34:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Recetario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Recetario` ;

-- -----------------------------------------------------
-- Schema Recetario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Recetario` ;
USE `Recetario` ;

-- -----------------------------------------------------
-- Table `Recetario`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recetario`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `Recetario`.`usuarios` (
  `idusuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apP` VARCHAR(45) NOT NULL,
  `apM` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Titular` INT NULL,
  `correo` VARCHAR(65) NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `fk_usuarios_usuarios1_idx` (`Titular` ASC),
  CONSTRAINT `fk_usuarios_usuarios1`
    FOREIGN KEY (`Titular`)
    REFERENCES `Recetario`.`usuarios` (`idusuarios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Recetario`.`recetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recetario`.`recetas` ;

CREATE TABLE IF NOT EXISTS `Recetario`.`recetas` (
  `idrecetas` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `tipoAlimentacion` VARCHAR(45) NULL,
  `porciones` DOUBLE NOT NULL,
  `Categoria` VARCHAR(45) NULL,
  `Region` VARCHAR(45) NULL,
  `creador` INT NOT NULL,
  `imagen` VARCHAR(200) NULL,
  PRIMARY KEY (`idrecetas`, `creador`),
  INDEX `fk_recetas_usuarios1_idx` (`creador` ASC),
  CONSTRAINT `fk_recetas_usuarios1`
    FOREIGN KEY (`creador`)
    REFERENCES `Recetario`.`usuarios` (`idusuarios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Recetario`.`favoritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recetario`.`favoritos` ;

CREATE TABLE IF NOT EXISTS `Recetario`.`favoritos` (
  `usuarios_idusuarios` INT NOT NULL,
  `recetas_idrecetas` INT NOT NULL,
  `fagregada` DATETIME NOT NULL,
  PRIMARY KEY (`usuarios_idusuarios`, `recetas_idrecetas`),
  INDEX `fk_usuarios_has_recetas_recetas1_idx` (`recetas_idrecetas` ASC),
  INDEX `fk_usuarios_has_recetas_usuarios_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_recetas_usuarios`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `Recetario`.`usuarios` (`idusuarios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuarios_has_recetas_recetas1`
    FOREIGN KEY (`recetas_idrecetas`)
    REFERENCES `Recetario`.`recetas` (`idrecetas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Recetario`.`ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recetario`.`ingredientes` ;

CREATE TABLE IF NOT EXISTS `Recetario`.`ingredientes` (
  `ingrediente` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`ingrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Recetario`.`recetasIngredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recetario`.`recetasIngredientes` ;

CREATE TABLE IF NOT EXISTS `Recetario`.`recetasIngredientes` (
  `recetas_idrecetas` INT NOT NULL,
  `ingredientes_ingrediente` VARCHAR(55) NOT NULL,
  `cantidad` DOUBLE NULL,
  `unidad` VARCHAR(6) NULL,
  PRIMARY KEY (`recetas_idrecetas`, `ingredientes_ingrediente`),
  INDEX `fk_recetas_has_ingredientes_recetas1_idx` (`recetas_idrecetas` ASC),
  INDEX `fk_recetasIngredientes_ingredientes1_idx` (`ingredientes_ingrediente` ASC),
  CONSTRAINT `fk_recetas_has_ingredientes_recetas1`
    FOREIGN KEY (`recetas_idrecetas`)
    REFERENCES `Recetario`.`recetas` (`idrecetas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recetasIngredientes_ingredientes1`
    FOREIGN KEY (`ingredientes_ingrediente`)
    REFERENCES `Recetario`.`ingredientes` (`ingrediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Recetario`.`usuariosAlergias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recetario`.`usuariosAlergias` ;

CREATE TABLE IF NOT EXISTS `Recetario`.`usuariosAlergias` (
  `usuarios_idusuarios` INT NOT NULL,
  `ingredientes_ingrediente` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`usuarios_idusuarios`, `ingredientes_ingrediente`),
  INDEX `fk_usuarios_has_alergias_usuarios1_idx` (`usuarios_idusuarios` ASC),
  INDEX `fk_usuariosAlergias_ingredientes1_idx` (`ingredientes_ingrediente` ASC),
  CONSTRAINT `fk_usuarios_has_alergias_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `Recetario`.`usuarios` (`idusuarios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuariosAlergias_ingredientes1`
    FOREIGN KEY (`ingredientes_ingrediente`)
    REFERENCES `Recetario`.`ingredientes` (`ingrediente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Recetario`.`Pasos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recetario`.`Pasos` ;

CREATE TABLE IF NOT EXISTS `Recetario`.`Pasos` (
  `numPasos` INT NOT NULL,
  `paso` LONGTEXT NOT NULL,
  `recetas_idrecetas` INT NOT NULL,
  `recetas_creador` INT NOT NULL,
  PRIMARY KEY (`numPasos`, `recetas_idrecetas`, `recetas_creador`),
  INDEX `fk_Pasos_recetas1_idx` (`recetas_idrecetas` ASC, `recetas_creador` ASC),
  CONSTRAINT `fk_Pasos_recetas1`
    FOREIGN KEY (`recetas_idrecetas` , `recetas_creador`)
    REFERENCES `Recetario`.`recetas` (`idrecetas` , `creador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
